export default [
    "Cantata One",
    "Fredericka the Great",
    "Acme",
    "Spicy Rice",
    "Ubuntu",
    "Concert One",
    "Swanky and Moo Moo",
    "Cagliostro",
    "Fredoka One",
    "Impact",
    "Graduate",
    "Chango",
    "Quantico",
    "Berkshire Swash",
    "Bangers",
    "Play",
    "Doppio One",
    "Bowlby One",
    "Francois One"
]