export default [
    "Acme",
    "Bangers",
    "Berkshire Swash",
    "Bowlby One",
    "Cagliostro",
    "Cantata One",
    "Chango",
    "Concert One",
    "Doppio One",
    "Francois One",
    "Fredericka the Great",
    "Fredoka One",
    "Graduate",
    "Impact",
    "Play",
    "Quantico",
    "Spicy Rice",
    "Swanky and Moo Moo",
    "Ubuntu",
]